"""index t_itinerary2route.route

Revision ID: 4b00542297d8
Revises: f6d6ef463e83
Create Date: 2026-01-01 13:10:47.870649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b00542297d8'
down_revision = 'f6d6ef463e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary2route', schema=None) as batch_op:
        batch_op.create_index('route_idx', ['route_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary2route', schema=None) as batch_op:
        batch_op.drop_index('route_idx')

    # ### end Alembic commands ###
