"""add month field

Revision ID: 98fb37c3e710
Revises: bb96cb60d9fc
Create Date: 2026-01-11 11:46:20.708302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fb37c3e710'
down_revision = 'bb96cb60d9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Text(length=11), sa.Computed("strftime('%Y-%m', local_departure)", persisted=True), nullable=False))
        batch_op.create_index('idx_itinerary_month_flyto_price', ['month', 'flyTo', 'price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_index('idx_itinerary_month_flyto_price')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
