"""add currency,fx_rate fields

Revision ID: bb96cb60d9fc
Revises: 4b00542297d8
Create Date: 2026-01-11 09:48:27.393299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb96cb60d9fc'
down_revision = '4b00542297d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), server_default=sa.text("'HUF'"), nullable=False))
        batch_op.add_column(sa.Column('fx_rate', sa.Float(), server_default='385.533292', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.drop_column('fx_rate')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
