"""initial migration

Revision ID: f6d6ef463e83
Revises: 
Create Date: 2025-12-26 15:46:09.827457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d6ef463e83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=26), nullable=False),
    sa.Column('combination_id', sa.String(length=24), nullable=False),
    sa.Column('flyFrom', sa.String(length=3), nullable=False),
    sa.Column('flyTo', sa.String(length=3), nullable=False),
    sa.Column('cityFrom', sa.String(length=50), nullable=False),
    sa.Column('cityCodeFrom', sa.String(length=3), nullable=False),
    sa.Column('cityTo', sa.String(length=50), nullable=False),
    sa.Column('cityCodeTo', sa.String(length=3), nullable=False),
    sa.Column('local_departure', sa.DateTime(), nullable=False),
    sa.Column('local_arrival', sa.DateTime(), nullable=False),
    sa.Column('airline', sa.String(length=2), nullable=False),
    sa.Column('flight_no', sa.Integer(), nullable=False),
    sa.Column('operating_carrier', sa.String(length=2), nullable=False),
    sa.Column('operating_flight_no', sa.String(length=4), nullable=False),
    sa.Column('fare_basis', sa.String(length=10), nullable=False),
    sa.Column('fare_category', sa.String(length=1), nullable=False),
    sa.Column('fare_classes', sa.String(length=1), nullable=False),
    sa.Column('_return', sa.Integer(), nullable=False),
    sa.Column('bags_recheck_required', sa.Boolean(), nullable=False),
    sa.Column('vi_connection', sa.Boolean(), nullable=False),
    sa.Column('guarantee', sa.Boolean(), nullable=False),
    sa.Column('equipment', sa.String(length=4), nullable=True),
    sa.Column('vehicle_type', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('rowid'),
    sa.UniqueConstraint('route_id')
    )
    op.create_table('search',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('range_start', sa.Date(), nullable=False),
    sa.Column('range_end', sa.Date(), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('rowid'),
    sa.UniqueConstraint('search_id')
    )
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_actual'), ['actual'], unique=False)

    op.create_table('itinerary',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.String(length=255), nullable=False),
    sa.Column('flyFrom', sa.String(length=3), nullable=False),
    sa.Column('flyTo', sa.String(length=3), nullable=False),
    sa.Column('cityFrom', sa.String(length=50), nullable=False),
    sa.Column('cityCodeFrom', sa.String(length=3), nullable=False),
    sa.Column('cityTo', sa.String(length=50), nullable=False),
    sa.Column('cityCodeTo', sa.String(length=3), nullable=False),
    sa.Column('countryFromCode', sa.String(length=2), nullable=False),
    sa.Column('countryFromName', sa.String(length=50), nullable=False),
    sa.Column('countryToCode', sa.String(length=2), nullable=False),
    sa.Column('countryToName', sa.String(length=50), nullable=False),
    sa.Column('local_departure', sa.DateTime(), nullable=False),
    sa.Column('local_arrival', sa.DateTime(), nullable=False),
    sa.Column('nightsInDest', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('durationDeparture', sa.Integer(), nullable=False),
    sa.Column('durationReturn', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('conversionEUR', sa.Float(), nullable=False),
    sa.Column('availabilitySeats', sa.Integer(), nullable=True),
    sa.Column('airlines', sa.String(length=30), nullable=False),
    sa.Column('booking_token', sa.String(length=2048), nullable=False),
    sa.Column('deep_link', sa.String(length=2048), nullable=False),
    sa.Column('facilitated_booking_available', sa.Boolean(), nullable=False),
    sa.Column('pnr_count', sa.Integer(), nullable=False),
    sa.Column('has_airport_change', sa.Boolean(), nullable=False),
    sa.Column('technical_stops', sa.Integer(), nullable=False),
    sa.Column('throw_away_ticketing', sa.Boolean(), nullable=False),
    sa.Column('hidden_city_ticketing', sa.Boolean(), nullable=False),
    sa.Column('virtual_interlining', sa.Boolean(), nullable=False),
    sa.Column('rlocal_departure', sa.DateTime(), nullable=True),
    sa.Column('rlocal_arrival', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search.rowid'], ),
    sa.PrimaryKeyConstraint('rowid'),
    sa.UniqueConstraint('search_id', 'itinerary_id')
    )
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_itinerary_id'), ['itinerary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_price'), ['price'], unique=False)
        batch_op.create_index('ix_itinerary_search_itinerary_id', ['search_id', 'itinerary_id'], unique=False)

    op.create_table('itinerary2route',
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.rowid'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.rowid'], ),
    sa.PrimaryKeyConstraint('itinerary_id', 'route_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary2route')
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_index('ix_itinerary_search_itinerary_id')
        batch_op.drop_index(batch_op.f('ix_itinerary_price'))
        batch_op.drop_index(batch_op.f('ix_itinerary_itinerary_id'))

    op.drop_table('itinerary')
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_actual'))

    op.drop_table('search')
    op.drop_table('route')
    # ### end Alembic commands ###
